import pytest
from arm_state import ArmState, MoltbookState
from budget import MetabolicBudget
from mantle import MantleOrchestrator
from reflex_arc import probe_context, reflect_schema

def test_simulation_workflow():
    budget = MetabolicBudget(initial_capacity=100.0)
    mantle = MantleOrchestrator(budget=budget)
    
    arm = ArmState(
        arm_id="arm_test_001",
        route="root->data_pipeline",
        moltbook=MoltbookState(
            status='ACTIVE',
            confidence_weight=1.0
        )
    )
    mantle.arms.append(arm)
    
    assert arm.execution_count == 0
    assert arm.moltbook.status == 'ACTIVE'
    
    # First action
    result_1 = probe_context(query='upstream variable', arm_state=arm)
    assert arm.execution_count == 1
    assert arm.moltbook.status == 'ACTIVE'
    assert "Context matching" in result_1
    assert "probe_context" in arm.moltbook.scratchpad or "Context matching" in arm.moltbook.scratchpad
    
    # Second action should trigger circuit breaker
    result_2 = reflect_schema(arm_state=arm)
    assert arm.execution_count == 1  # Not incremented due to limit
    assert arm.moltbook.status == 'SEAL'
    assert "CIRCUIT BREAKER TRIGGERED" in result_2
    
    # Mantle evaluation
    mantle.run_cycle()
    
    # Validate final mantle state
    final_status = mantle.arms[0].moltbook.status
    assert final_status == 'ACTIVE'  # Because it gets regenerated by regrow_arm
